
package steve.dev.proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.dev.steve/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://ws.dev.steve/", className = "steve.dev.proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://ws.dev.steve/", className = "steve.dev.proxy.ConvertResponse")
    @Action(input = "http://ws.dev.steve/BanqueService/ConvertRequest", output = "http://ws.dev.steve/BanqueService/ConvertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<steve.dev.proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://ws.dev.steve/", className = "steve.dev.proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://ws.dev.steve/", className = "steve.dev.proxy.ListComptesResponse")
    @Action(input = "http://ws.dev.steve/BanqueService/listComptesRequest", output = "http://ws.dev.steve/BanqueService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param code
     * @return
     *     returns steve.dev.proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getcompte", targetNamespace = "http://ws.dev.steve/", className = "steve.dev.proxy.Getcompte")
    @ResponseWrapper(localName = "getcompteResponse", targetNamespace = "http://ws.dev.steve/", className = "steve.dev.proxy.GetcompteResponse")
    @Action(input = "http://ws.dev.steve/BanqueService/getcompteRequest", output = "http://ws.dev.steve/BanqueService/getcompteResponse")
    public Compte getcompte(
        @WebParam(name = "Code", targetNamespace = "")
        int code);

}
